mui instaled
oicrruf/insurance-web pull request #8
Opened 2022-04-06 03:43 UTC by rogeliomx

2022-04-06 04:00 UTC, oicrruf requested changes
Debes de agregar el cdn de la fuente en el archivo: 

`public/index.html`

```
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
/>
```

2022-04-06 04:00 UTC, oicrruf commented on package.json
>      "@testing-library/jest-dom": "^5.16.3",
Te faltó agregar los iconos de MUI

`npm install @mui/icons-material`

2022-04-06 04:15 UTC, oicrruf approved these changes

2022-04-12 22:06 UTC, visualxerox approved these changes

2022-04-13 16:05 UTC, merged