2 create home component
oicrruf/insurance-web pull request #9
Opened 2022-04-08 04:50 UTC by rogeliomx

Hola, hice el home component, al parecer me faltan lo del package.json y ver si esta bien el atomic design. @visualxerox Me podrias apoyar en lo faltante te agradezco

🍀

2022-04-12 14:55 UTC, oicrruf requested changes

2022-04-12 14:55 UTC, oicrruf commented on src/components/home.js
> +export class Home extends Component {
Vamos a trabajar con React funcional, esto es por clases. Cambialo a React por funciones, por fa 🤓

2022-04-22 17:12 UTC, oicrruf approved these changes

2022-04-22 17:19 UTC, visualxerox approved these changes
Gracias @oicrruf

2022-04-23 01:27 UTC, merged